// features/home/data/mock.ts

import { ProductViewModel } from "@/features/shop/types/productMapper";

export const newestProducts: ProductViewModel[] = [
    {
        id: "1",
        name: "کیف دستی چرم کلاسیک",
        title: "کیف دستی چرم کلاسیک",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 2890000,
        originalPrice: 3490000,
        hasDiscount: true,
        discountPercent: 18,
        isNew: true,
        isBestSeller: false,
        stock: 12,
        views: 420,
        category: "bags",
        categoryLabel: "کیف",
        type: "handbag",
        typeLabel: "دستی",
        tags: ["natural-leather", "premium"],
        tagLabels: ["چرم طبیعی", "پریمیوم"],
        isOutOfStock: false,
    },

    {
        id: "2",
        name: "کفش رسمی مردانه",
        title: "کفش رسمی مردانه",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 4190000,
        originalPrice: 4190000,
        hasDiscount: false,
        discountPercent: 0,
        isNew: true,
        isBestSeller: true,
        stock: 8,
        views: 910,
        category: "shoes",
        categoryLabel: "کفش",
        type: "formal",
        typeLabel: "رسمی",
        tags: ["luxury", "handmade"],
        tagLabels: ["لوکس", "دست‌دوز"],
        isOutOfStock: false,
    },

    {
        id: "3",
        name: "کمربند مینیمال",
        title: "کمربند مینیمال",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 990000,
        originalPrice: 1290000,
        hasDiscount: true,
        discountPercent: 24,
        isNew: true,
        isBestSeller: false,
        stock: 20,
        views: 280,
        category: "accessories",
        categoryLabel: "اکسسوری",
        type: "belt",
        typeLabel: "کمربند",
        tags: ["minimal", "natural-leather"],
        tagLabels: ["مینیمال", "چرم طبیعی"],
        isOutOfStock: false,
    },
    {
        id: "4",
        name: "کمربند مینیمال",
        title: "کمربند مینیمال",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 990000,
        originalPrice: 1290000,
        hasDiscount: true,
        discountPercent: 24,
        isNew: true,
        isBestSeller: false,
        stock: 20,
        views: 280,
        category: "accessories",
        categoryLabel: "اکسسوری",
        type: "belt",
        typeLabel: "کمربند",
        tags: ["minimal", "natural-leather"],
        tagLabels: ["مینیمال", "چرم طبیعی"],
        isOutOfStock: false,
    },
    {
        id: "5",
        name: "کمربند مینیمال",
        title: "کمربند مینیمال",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 990000,
        originalPrice: 1290000,
        hasDiscount: true,
        discountPercent: 24,
        isNew: true,
        isBestSeller: false,
        stock: 20,
        views: 280,
        category: "accessories",
        categoryLabel: "اکسسوری",
        type: "belt",
        typeLabel: "کمربند",
        tags: ["minimal", "natural-leather"],
        tagLabels: ["مینیمال", "چرم طبیعی"],
        isOutOfStock: false,
    },
    {
        id: "6",
        name: "کمربند مینیمال",
        title: "کمربند مینیمال",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 990000,
        originalPrice: 1290000,
        hasDiscount: true,
        discountPercent: 24,
        isNew: true,
        isBestSeller: false,
        stock: 20,
        views: 280,
        category: "accessories",
        categoryLabel: "اکسسوری",
        type: "belt",
        typeLabel: "کمربند",
        tags: ["minimal", "natural-leather"],
        tagLabels: ["مینیمال", "چرم طبیعی"],
        isOutOfStock: false,
    },
    {
        id: "7",
        name: "کمربند مینیمال",
        title: "کمربند مینیمال",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 990000,
        originalPrice: 1290000,
        hasDiscount: true,
        discountPercent: 24,
        isNew: true,
        isBestSeller: false,
        stock: 20,
        views: 280,
        category: "accessories",
        categoryLabel: "اکسسوری",
        type: "belt",
        typeLabel: "کمربند",
        tags: ["minimal", "natural-leather"],
        tagLabels: ["مینیمال", "چرم طبیعی"],
        isOutOfStock: false,
    },
];

export const mostViewedProducts: ProductViewModel[] = [
    {
        id: "4",
        name: "کیف دوشی زنانه",
        title: "کیف دوشی زنانه",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 3590000,
        originalPrice: 3990000,
        hasDiscount: true,
        discountPercent: 10,
        isNew: false,
        isBestSeller: true,
        stock: 5,
        views: 1840,
        category: "bags",
        categoryLabel: "کیف",
        type: "shoulder-bag",
        typeLabel: "دوشی",
        tags: ["best-seller", "premium"],
        tagLabels: ["پرفروش", "پریمیوم"],
        isOutOfStock: false,
    },

    {
        id: "5",
        name: "بوت چرمی زمستانی",
        title: "بوت چرمی زمستانی",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 5290000,
        originalPrice: 6290000,
        hasDiscount: true,
        discountPercent: 16,
        isNew: false,
        isBestSeller: true,
        stock: 2,
        views: 2310,
        category: "shoes",
        categoryLabel: "کفش",
        type: "boots",
        typeLabel: "بوت",
        tags: ["winter", "luxury"],
        tagLabels: ["زمستانه", "لوکس"],
        isOutOfStock: false,
    },

    {
        id: "6",
        name: "کیف لپ‌تاپ چرمی",
        title: "کیف لپ‌تاپ چرمی",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 4790000,
        originalPrice: 4790000,
        hasDiscount: false,
        discountPercent: 0,
        isNew: false,
        isBestSeller: true,
        stock: 0,
        views: 3120,
        category: "bags",
        categoryLabel: "کیف",
        type: "laptop-bag",
        typeLabel: "لپ‌تاپ",
        tags: ["office", "premium"],
        tagLabels: ["اداری", "پریمیوم"],
        isOutOfStock: true,
    },
    {
        id: "7",
        name: "کیف لپ‌تاپ چرمی",
        title: "کیف لپ‌تاپ چرمی",
        imgUrl:
            "/images/womens-category.jpg",
        finalPrice: 4790000,
        originalPrice: 4790000,
        hasDiscount: false,
        discountPercent: 0,
        isNew: false,
        isBestSeller: true,
        stock: 0,
        views: 3120,
        category: "bags",
        categoryLabel: "کیف",
        type: "laptop-bag",
        typeLabel: "لپ‌تاپ",
        tags: ["office", "premium"],
        tagLabels: ["اداری", "پریمیوم"],
        isOutOfStock: true,
    },
];